import {sprite,text} from '../draw.js';
import {makeCourse} from '../golf-course.js';
import {GolfPhysics,golfPull} from './golf-physics.js';
import {createGolfCamera,stepGolfCamera,golfCameraView} from '../golf-camera.js';
import {createGolfBallVisual,blinkGolfBall,unblinkGolfBall,setGolfBallAim,hideGolfBallDots,updateGolfBallVisual,describeGolfBallVisual} from '../golf-ball-visual.js';
export {makeCourse,rng} from '../golf-course.js';
export class GolfRules{
 constructor(holes=3){this.holes=holes;this.hole=1;this.player=0;this.strokes=[0,0];this.done=[false,false];this.winner=undefined;}
 shoot(){if(this.done[this.player]||this.winner!==undefined)return false;this.strokes[this.player]++;return true;}
 settle(sunk=false){if(sunk)this.done[this.player]=true;if(this.done.every(Boolean)){
 if(this.hole===this.holes){this.winner=this.strokes[0]===this.strokes[1]?null:this.strokes[0]<this.strokes[1]?0:1;return {complete:true};}
 this.hole++;this.done=[false,false];this.player=0;return {newHole:true};
 }if(sunk&&!this.done[1-this.player])this.player=1-this.player;return {};}
}
export default class Golf{
 constructor(h,{seed=(Date.now()>>>0)%1000000}={}){this.h=h;this.rules=new GolfRules();this.seed=seed;this.course=makeCourse(this.seed);this.balls=[0,1].map(()=>({...this.course.start,vx:0,vy:0}));this.resetVisuals();this.flag={offset:18,alpha:1};this.power=45;this.angle=-Math.PI/2;h.controls('<label>Course <select id="holes"><option value="3">3 holes</option><option value="5">5 holes</option></select></label><label>Power <input id="power" type="range" min="5" max="100" value="45"></label><button id="putt" class="primary">Putt</button><button id="golf-zoom">Overview</button><p>Drag from the ball to aim, pull back and release to putt.</p>');h.onControl('#holes','change',e=>{if(this.rules.strokes.every(n=>n===0)){this.rules.holes=+e.target.value;this.course=makeCourse(this.seed,1,this.rules.holes);this.balls=[0,1].map(()=>({...this.course.start,vx:0,vy:0}));this.resetVisuals();this.message();}});h.onControl('#power','input',e=>{this.power=+e.target.value;this.aimed=true;this.visuals[this.rules.player]=unblinkGolfBall(this.visuals[this.rules.player]);});h.onControl('#putt','click',()=>this.shoot());h.onControl('#golf-zoom','click',e=>{this.camera.zoom=true;e.target.hidden=true;});this.message();}
 resetVisuals(){this.resetCamera();this.aimed=false;this.visuals=this.balls.map(()=>blinkGolfBall(createGolfBallVisual(),Math.random()));}
 message(){this.h.status(`Hole ${this.rules.hole}/${this.rules.holes} · Strokes ${this.rules.strokes[0]} – ${this.rules.strokes[1]}`);}
 resetCamera(){this.camera=createGolfCamera(this.course,this.balls[this.rules.player]);this.cameraRemainder=0;const button=globalThis.document?.querySelector('#golf-zoom');if(button)button.hidden=false;}
 pointerDown(p){if(this.camera.zoom){this.camera.zoom=false;const button=globalThis.document?.querySelector('#golf-zoom');if(button)button.hidden=false;return;}if(this.moving||this.rules.done[this.rules.player])return;this.drag={...p};this.aim={...p};this.power=0;this.visuals[this.rules.player]=unblinkGolfBall(this.visuals[this.rules.player]);}
 pointerMove(p){if(!this.drag||this.moving)return;this.aim=p;const dx=this.drag.x-p.x,dy=this.drag.y-p.y,d=Math.hypot(dx,dy);if(d>0)this.angle=Math.atan2(dy,dx);this.power=golfPull(d)/3;this.aimed=true;const el=globalThis.document?.querySelector('#power');if(el)el.value=this.power;}
 pointerUp(p){if(p)this.pointerMove(p);if(this.drag&&this.power>0)this.shoot();this.drag=null;}
 shoot(){if(this.moving||this.power<=0||!this.rules.shoot())return;const choose=globalThis.document?.querySelector('#holes');if(choose)choose.disabled=true;const b=this.balls[this.rules.player];this.last={x:b.x,y:b.y};this.aimed=false;this.visuals[this.rules.player]=hideGolfBallDots(unblinkGolfBall(this.visuals[this.rules.player]));this.physics?.destroy();this.physics=new GolfPhysics(this.course,b,{onContact:contact=>{this.h.sound(contact.bouncy?'golf_bumper7.mp3':'golf_hit.mp3');if(contact.bouncy)contact.obstacle.bounceTime=0;},onInside:()=>this.h.sound('golf_sink.mp3')});this.physics.strike(this.angle,this.power*3);this.moving=true;this.h.sound('golf_shoot.mp3');this.message();}
 update(dt){const active=this.rules.player;this.visuals[active]=updateGolfBallVisual(this.visuals[active],dt,{ballScale:this.balls[active].scale??1});const ball=this.balls[this.rules.player],near=Math.hypot(ball.x-this.course.hole.x,ball.y-this.course.hole.y)<30,targetAlpha=near?0:1;if((near&&this.flag.alpha>.99)||(!near&&this.flag.alpha<.01))this.h.sound(`SWORD SWISHES 1_0${2+Math.floor(Math.random()*4)}.mp3`);const blend=1-Math.pow(.9,dt*60);this.flag.offset+=((near?55:18)-this.flag.offset)*blend;this.flag.alpha+=(targetAlpha-this.flag.alpha)*blend;for(const o of this.course.obstacles)if(o.bounceTime!==undefined){o.bounceTime+=dt;if(o.bounceTime>=.16)delete o.bounceTime;}this.cameraRemainder+=Math.min(dt,.25);while(this.cameraRemainder+1e-12>=1/60){this.cameraRemainder-=1/60;stepGolfCamera(this.camera,this.course,this.balls[this.rules.player],{selected:!!this.drag,pull:this.power*3});if(this.moving&&!this.physics.step(1/60))this.settle(!!this.balls[this.rules.player].inside);}}
 settle(sunk){this.moving=false;const old=this.rules.player;const result=this.rules.settle(sunk);if(!sunk)this.visuals[old]=blinkGolfBall(this.visuals[old],Math.random());else if(old!==this.rules.player&&!result.newHole)this.visuals[this.rules.player]=blinkGolfBall(createGolfBallVisual(),Math.random());if(result.newHole){this.course=makeCourse(this.seed,this.rules.hole,this.rules.holes);this.balls=[0,1].map(()=>({...this.course.start,vx:0,vy:0}));this.resetVisuals();this.angle=-Math.PI/2;this.flag={offset:18,alpha:1};}this.message();if(this.rules.winner!==undefined){this.h.finish(this.rules.winner,`Final strokes: ${this.rules.strokes[0]} – ${this.rules.strokes[1]}`);return;}if(result.newHole)this.h.turn(this.rules.player,`Hole ${this.rules.hole} of ${this.rules.holes}. Both players use the same course.`);else if(old!==this.rules.player){this.resetCamera();this.h.turn(this.rules.player,sunk?'Your opponent finished. Complete the course in fewer strokes.':'Your putt.');}}
 view(){return golfCameraView(this.camera,this.course);}
 local(p){const v=this.view();return {x:(p.x-v.x)/v.scale,y:(p.y-v.y)/v.scale};}
 destroy(){this.physics?.destroy();this.physics=null;}
 draw(c){c.fillStyle=this.course.background;c.fillRect(0,0,420,700);const v=this.view();c.save();c.translate(v.x,v.y);c.scale(v.scale,v.scale);for(const [x,y]of this.course.tiles){const corner=this.course.cornerTiles.find(p=>p.x===x&&p.y===y);c.save();c.translate((x+.5)*65,(y+.5)*65);if(corner)c.rotate(corner.rotation);if(!sprite(c,this.h.assets,corner?'golf_tile2':'golf_tile',corner?-33:-32.5,corner?-33:-32.5,corner?66:65,corner?66:65)){c.fillStyle='#43bb6f';c.fillRect(-32.5,-32.5,65,65);}c.restore();}for(const slope of this.course.slopes){c.save();c.translate((slope.x+.5)*65,(slope.y+.5)*65);c.rotate(slope.rotation);sprite(c,this.h.assets,slope.asset,-32.5,-26,65,52);c.restore();}for(const w of this.course.walls){const dx=w.bx-w.ax,dy=w.by-w.ay,len=Math.hypot(dx,dy);c.save();c.translate((w.ax+w.bx)/2+dy/len*3,(w.ay+w.by)/2-dx/len*3);c.rotate(Math.atan2(dy,dx));sprite(c,this.h.assets,w.asset||'golf_wall',w.asset?-50.5:-len/2,-3,w.asset?101:len,6);c.restore();}for(const o of this.course.obstacles){const im=this.h.assets[o.asset];if(!im)continue;const bounce=o.bounceTime===undefined?1:o.bounceTime<.01?1+.35*o.bounceTime/.01:1.35-.35*(o.bounceTime-.01)/.15;const w=im.width/3*o.scale*bounce,h=im.height/3*o.scale*bounce;c.save();c.translate(o.shadow.x,o.shadow.y);c.rotate(o.shadow.rotation);c.globalAlpha=o.shadow.alpha;c.filter="brightness(0)";c.drawImage(im,-w/2,-h/2,w,h);c.restore();c.save();c.translate(o.x,o.y);c.rotate(o.rotation);c.drawImage(im,-w/2,-h/2,w,h);c.restore();}const h=this.course.hole;sprite(c,this.h.assets,'golf_hole',h.x-5.5,h.y-5.5,11,11);c.globalAlpha=this.flag.alpha;sprite(c,this.h.assets,'golf_flag',h.x-21,h.y-21-this.flag.offset,42,42);c.globalAlpha=1;for(let p=0;p<2;p++){if(this.rules.done[p]||p!==this.rules.player)continue;const b=this.balls[p];let state=this.visuals[p];if(!this.moving&&this.aimed)state=setGolfBallAim(state,this.angle,this.power*3);const visual=describeGolfBallVisual(state,{x:b.x,y:b.y,scale:b.scale??1,alpha:b.alpha??1});for(const part of [visual.shadow,visual.halo,...visual.aim,visual.ball]){if(part.hidden||part.alpha<=0)continue;c.save();c.globalAlpha=part.alpha;if(part.tint==='#000000')c.filter='brightness(0)';sprite(c,this.h.assets,part.asset,part.x-part.width/2,part.y-part.height/2,part.width,part.height);c.restore();}}c.restore();text(c,`Hole ${this.rules.hole}/${this.rules.holes}`,210,55,25,'#666');}
}
