import {poolPockets,poolBallRadius,rackPosition,cueStart,rackDensities,placeCue,cueReset,nativeToCanvas,POOL_TABLE} from './pool-table.js';
import {PoolPhysics,POOL_NATIVE} from './pool-physics.js';
import {readTexture,makeBall} from '../ball-texture.js';
import {POOL_VISUAL,initializeBallVisual,observePoolRoll,cuePose,cueAnimation} from './pool-rendering.js';
import {PoolAim,PoolPocketPresentation,drawPoolAim} from './pool-presentation.js';
import {sprite,circle,text} from '../draw.js';
const colors=['#fff','#f4cc1b','#255bb4','#d63432','#793ca5','#e87620','#21854d','#9e2939','#17191b'];
export const groupOf=n=>n>0&&n<8?'solid':n>8?'stripes':null;
export function resolvePoolShot({player,groups,pocketed,firstHit,rail,breakShot,calledPocket,eightPocket,remaining}){
 let foul=firstHit===null||pocketed.includes(0);
 const assigned=groups[player],onEight=assigned&&remaining[assigned]===0;
 if(!breakShot&&assigned&&firstHit!==null&&(onEight?firstHit!==8:groupOf(firstHit)!==assigned))foul=true;
 if(pocketed.includes(8)&&!breakShot)return {winner:!foul&&onEight&&calledPocket===eightPocket?player:1-player,foul,groups,next:player};
 const nextGroups=[...groups];if(!breakShot&&!assigned){const n=pocketed.find(n=>groupOf(n));if(n){nextGroups[player]=groupOf(n);nextGroups[1-player]=n<8?'stripes':'solid';}}
 const keep=!foul&&pocketed.some(n=>groupOf(n)&&(breakShot||groupOf(n)===nextGroups[player]));return {foul,groups:nextGroups,next:keep?player:1-player,winner:null,respotEight:breakShot&&pocketed.includes(8)};
}
export default class Pool{
 constructor(h,{random=Math.random}={}){this.h=h;this.random=random;this.player=0;this.groups=[null,null];this.r=poolBallRadius;this.pockets=poolPockets;this.balls=[{n:0,...cueStart,vx:0,vy:0,out:false}];let ids=[1,10,2,3,8,11,12,4,13,5,6,14,7,15,9],k=0,densities=rackDensities(random);for(let row=0;row<5;row++)for(let col=0;col<=row;col++)this.balls.push({n:ids[k++],...rackPosition(row,col),density:densities[row][col],vx:0,vy:0,out:false});this.textures={};for(const b of this.balls)initializeBallVisual(b);for(let n=0;n<=15;n++){const im=h.assets['pool_ball'+String(n||16).padStart(4,'0')];if(im)this.textures[n]=readTexture(im);}this.angle=-Math.PI/2;this.breakShot=true;this.hand=false;this.power=55;this.calledPocket=null;this.aim=new PoolAim();this.pocketPresentation=new PoolPocketPresentation();this.physics=new PoolPhysics(this.balls,{radius:this.r,pockets:this.pockets,onBallContact:(a,b)=>{if(this.firstHit===null&&(a.n===0||b.n===0))this.firstHit=a.n===0?b.n:a.n;this.h.sound('pool_hit1.mp3');},onRail:()=>{this.rail=true;this.h.sound('pool_cushion.mp3');},onPocket:(ball,index)=>{this.pocketPresentation.enter(ball,ball.presentationSnapshot);this.pocketed.push(ball.n);if(ball.n===8)this.eightPocket=index;this.h.sound('pool_pocket.mp3');}});this.releaseRollObserver=observePoolRoll(this.physics);this.cueRevealAge=POOL_VISUAL.fadeIn;this.controls();this.message();}
 controls(){this.h.controls('<label>Power <input id="power" type="range" min="5" max="100" value="55"></label><button id="shoot" class="primary">Shoot</button><button id="spin">Spin</button><p>Drag to aim. Choose a pocket when shooting the 8 ball.</p>');this.h.onControl('#power','input',e=>this.power=+e.target.value);this.h.onControl('#shoot','click',()=>this.shoot());this.h.onControl('#spin','click',()=>{this.spinMode=!this.spinMode;this.h.status(this.spinMode?'Tap the cue ball inset to set spin.':'Drag to aim, then shoot.');});}
 message(){const g=this.groups[this.player];this.h.status(this.hand?'Ball in hand · drag the cue ball to place it.':g?`${g==='solid'?'Solids':'Stripes'} · ${this.balls.filter(b=>!b.out&&groupOf(b.n)===g).length} left`:'Open table · drag to aim and shoot.');}
 pointerDown(p){if(this.moving)return;if(this.spinMode){const x=(p.x-365)/35,y=(p.y-35)/35,scale=Math.max(1,Math.hypot(x,y));this.spin={x:x/scale,y:y/scale};this.spinMode=false;return;}if(this.onEight()){const pi=this.pockets.findIndex(v=>Math.hypot(p.x-v[0],p.y-v[1])<24);if(pi>=0){this.calledPocket=pi;this.h.status('Pocket called. Aim and shoot.');return;}}this.drag=true;this.pointerMove(p);}
 pointerMove(p){if(!this.drag||this.moving)return;const cue=this.balls[0];if(this.hand){const placed=placeCue(p.x,p.y,this.balls,this.breakShot);if(placed){cue.x=placed.x;cue.y=placed.y;cue.out=false;}}else this.angle=Math.atan2(p.y-cue.y,p.x-cue.x);}
 pointerUp(){this.drag=false;if(this.hand)this.hand=false;this.message();}
 onEight(){return this.groups[this.player]&&this.balls.every(b=>b.out||groupOf(b.n)!==this.groups[this.player]);}
 shoot(){if(this.moving||this.hand)return;if(this.onEight()&&this.calledPocket===null){this.h.status('Choose one of the six pockets for the 8 ball.');return;}const b=this.balls[0];if(b.out)return;this.startRemaining={solid:this.balls.filter(b=>!b.out&&groupOf(b.n)==='solid').length,stripes:this.balls.filter(b=>!b.out&&groupOf(b.n)==='stripes').length};this.physics.syncFromBalls();this.shotAnimation={age:0,guide:this.getAim(),ball:{x:b.x,y:b.y},angle:this.angle,power:this.power,spin:this.spin};this.shotPending=true;this.moving=true;this.firstHit=null;this.pocketed=[];this.rail=false;this.eightPocket=null;}
 update(dt){this.pocketPresentation.step(dt);this.cueRevealAge=Math.min(POOL_VISUAL.fadeIn,this.cueRevealAge+dt);if(this.shotAnimation)this.shotAnimation.age+=dt;if(!this.moving)return;if(this.shotPending){if(this.shotAnimation.age<POOL_VISUAL.strikeDuration)return;this.shotPending=false;this.physics.strikeCue(this.shotAnimation.angle,this.shotAnimation.power/100*POOL_NATIVE.maxPower,this.shotAnimation.spin);this.h.sound('pool_hit.mp3');dt=Math.max(0,this.shotAnimation.age-POOL_VISUAL.strikeDuration);}if(!this.physics.step(dt))this.endShot();}
 endShot(){this.moving=false;this.shotAnimation=null;this.cueRevealAge=0;this.physics.stop();const r=resolvePoolShot({player:this.player,groups:this.groups,pocketed:this.pocketed,firstHit:this.firstHit,rail:this.rail,breakShot:this.breakShot,calledPocket:this.calledPocket,eightPocket:this.eightPocket,remaining:this.startRemaining});this.breakShot=false;this.spin=null;this.groups=r.groups;this.calledPocket=null;if(r.respotEight){const eight=this.balls.find(b=>b.n===8),start=nativeToCanvas(560+this.random()*2-1,220+this.random()*2-1),placed=placeCue(start.x,start.y,this.balls,false,8);if(placed)Object.assign(eight,{...placed,vx:0,vy:0,out:false});}if(r.winner!==null){this.h.finish(r.winner,'The 8 ball decided the game.');return;}const old=this.player;this.player=r.next;if(r.foul){this.hand=true;this.balls[0].out=false;const reset=placeCue(cueReset.x,cueReset.y,this.balls)||cueReset;Object.assign(this.balls[0],reset);}this.message();if(old!==this.player)this.h.turn(this.player,r.foul?'Foul. You have ball in hand.':'Your shot.');}
 destroy(){this.releaseRollObserver();this.physics.destroy();this.pocketPresentation.destroy();}
 getAim(){const key=[this.angle,this.player,this.groups[this.player],this.breakShot,this.calledPocket,...this.balls.flatMap(b=>[b.x,b.y,b.out])].join(':');if(key!==this.aimKey){this.aimGuide=this.aim.build(this.balls,this.angle,{breakShot:this.breakShot,group:this.groups[this.player],calledPocket:this.calledPocket});this.aimKey=key;}return this.aimGuide;}
 drawBallShadow(c,b){const width=POOL_VISUAL.shadowSize*POOL_TABLE.scaleX,height=POOL_VISUAL.shadowSize*POOL_TABLE.scaleY;c.save();c.globalAlpha=POOL_VISUAL.shadowAlpha;sprite(c,this.h.assets,'pool_ball_shadow',b.x-width/2,b.y+POOL_VISUAL.shadowOffset*POOL_TABLE.scaleY-height/2,width,height);c.restore();}
 drawBall(c,b){const sizeX=POOL_VISUAL.ballSize*POOL_TABLE.scaleX,sizeY=POOL_VISUAL.ballSize*POOL_TABLE.scaleY,shadeX=POOL_VISUAL.shadeSize*POOL_TABLE.scaleX,shadeY=POOL_VISUAL.shadeSize*POOL_TABLE.scaleY;if(this.textures[b.n]){if(b.phase!==b.visualVersion){b.visual=makeBall(this.textures[b.n],b.textureQuaternion);b.phase=b.visualVersion;}c.drawImage(b.visual,b.x-sizeX/2,b.y-sizeY/2,sizeX,sizeY);}else{circle(c,b.x,b.y,this.r,colors[b.n>8?b.n-8:b.n]);if(b.n){circle(c,b.x,b.y,4,'#fff');text(c,''+b.n,b.x,b.y+2.5,6,'#111');}}sprite(c,this.h.assets,'pool_ball_shade',b.x-shadeX/2,b.y-shadeY/2,shadeX,shadeY);}
 draw(c){
  c.fillStyle='#eee';c.fillRect(0,0,420,700);
  // Source board_black z0 is board_top.size minus 55 SpriteKit points.
  const floorWidth=420-55*POOL_TABLE.scaleX,floorHeight=690-55*POOL_TABLE.scaleY;c.fillStyle='#000';c.fillRect(210-floorWidth/2,360-floorHeight/2,floorWidth,floorHeight);
  // Captured sprite/shade/shadow become z1, below the original cloth(z2)
  // and cushion artwork(z20). Neither alpha nor size changes on capture.
  for(const {visual}of this.pocketPresentation.entries){this.drawBallShadow(c,visual);this.drawBall(c,visual);}
  sprite(c,this.h.assets,'pool_board_green',58,78,304,568);
  for(const b of this.balls)if(!b.out)this.drawBallShadow(c,b);
  for(const b of this.balls)if(!b.out)this.drawBall(c,b);
  const b=this.balls[0],animation=this.shotAnimation,timing=animation?cueAnimation(animation.age,animation.power):{pullback:POOL_VISUAL.pullback*this.power/100,alpha:Math.min(1,this.cueRevealAge/POOL_VISUAL.fadeIn)},visible=(!this.moving&&!b.out)||animation;
  if(visible)drawPoolAim(c,animation?.guide||this.getAim(),animation?timing.aimAlpha:timing.alpha);
  sprite(c,this.h.assets,'pool_board_top',0,15,420,690);
  for(const [i,p]of this.pockets.entries())if(this.calledPocket===i){c.strokeStyle='#ffe379';c.lineWidth=3;c.beginPath();c.arc(...p,19,0,Math.PI*2);c.stroke();}
  if(visible&&timing.alpha>0){const pose=cuePose(animation?.ball||b,animation?.angle??this.angle,timing.pullback),width=POOL_VISUAL.cueWidth,height=POOL_VISUAL.cueHeight,shadowHeight=POOL_VISUAL.cueShadowHeight;c.save();c.globalAlpha=timing.alpha;c.save();c.translate(pose.x,pose.y+POOL_VISUAL.cueShadowOffset*POOL_TABLE.scaleY);c.transform(...pose.matrix,0,0);sprite(c,this.h.assets,'pool_cue_shadow',-width/2,-shadowHeight/2,width,shadowHeight);c.restore();c.translate(pose.x,pose.y);c.transform(...pose.matrix,0,0);sprite(c,this.h.assets,'pool_cue',-width/2,-height/2,width,height);c.restore();}
  if(this.spinMode){sprite(c,this.h.assets,'pool_cue_ball',335,0,60,70);sprite(c,this.h.assets,'pool_cue_dot',365+(this.spin?.x||0)*25-6.5,35+(this.spin?.y||0)*25-6.5,13,13);}
 }
}
