import {SeaClouds} from '../sea-stage.js';
import {SeaWaterSurface} from '../sea-water.js';
import {SeaParticles} from '../sea-particles.js';
import {SEA_NATIVE,seaFlight,seaBomb,seaWaterRipple,seaWaterMarker,makeSeaShake,seaShakeOffset} from '../sea-animation.js';
// Native SeaSettings tags 1–3, serialized by requestStart: as length-4/3/2/1 counts.
export const SEA_PRESETS=[
  {size:10,texture:'sea_grid',mode:'1,2,3,4',fleet:[4,3,3,2,2,2,1,1,1,1]},
  {size:9,texture:'sea_grid2',mode:'3,5,0,0',fleet:[4,4,4,3,3,3,3,3]},
  {size:8,texture:'sea_grid4',mode:'1,3,3,0',fleet:[4,3,3,3,2,2,2]},
];
export const DEFAULT_FLEET=SEA_PRESETS[0].fleet;
export class SeaRules {
  constructor(size=10,fleet=SEA_PRESETS.find(p=>p.size===size)?.fleet||DEFAULT_FLEET){this.size=size;this.fleet=[...fleet];this.ships=[[],[]];this.shots=[new Map(),new Map()];this.revealedWater=[new Set(),new Set()];this.player=2;this.finished=false;this.winner=null;}
  cells(x,y,length,vertical){return Array.from({length},(_,i)=>[x+(vertical?0:i),y+(vertical?i:0)]);}
  canPlace(player,index,x,y,vertical){if(!Number.isInteger(x)||!Number.isInteger(y)||!this.fleet[index])return false;const cells=this.cells(x,y,this.fleet[index],vertical);if(cells.some(([cx,cy])=>cx<0||cy<0||cx>=this.size||cy>=this.size))return false;
    return !this.ships[player-1].some((ship,i)=>i!==index&&ship&&ship.cells.some(([sx,sy])=>cells.some(([cx,cy])=>Math.abs(sx-cx)<=1&&Math.abs(sy-cy)<=1)));
  }
  place(player,index,x,y,vertical){if(!this.canPlace(player,index,x,y,vertical))return false;this.ships[player-1][index]={x,y,vertical,length:this.fleet[index],cells:this.cells(x,y,this.fleet[index],vertical)};return true;}
  arranged(player){return this.fleet.every((_,index)=>!!this.ships[player-1][index]);}
  clear(player){this.ships[player-1]=[];}
  // Randomized backtracking enforces the same no-touch invariant as manual placement.
  randomize(player,random=Math.random){this.clear(player);const search=(index)=>{if(index===this.fleet.length)return true;const choices=[];for(let y=0;y<this.size;y++)for(let x=0;x<this.size;x++)for(const vertical of [false,true])choices.push({x,y,vertical});for(let i=choices.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[choices[i],choices[j]]=[choices[j],choices[i]];}for(const p of choices){if(this.place(player,index,p.x,p.y,p.vertical)&&search(index+1))return true;this.ships[player-1][index]=undefined;}return false;};return search(0);}
  fire(x,y){if(this.finished||!this.arranged(1)||!this.arranged(2)||!Number.isInteger(x)||!Number.isInteger(y)||x<0||y<0||x>=this.size||y>=this.size)return null;const player=this.player,key=`${x},${y}`,shots=this.shots[player-1];if(shots.has(key)||this.revealedWater[player-1].has(key))return null;const enemy=this.ships[2-player];const ship=enemy.find(s=>s.cells.some(([cx,cy])=>cx===x&&cy===y));shots.set(key,!!ship);const sunk=ship&&ship.cells.every(([cx,cy])=>shots.get(`${cx},${cy}`));if(sunk)for(const [sx,sy] of ship.cells)for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const cx=sx+dx,cy=sy+dy,k=`${cx},${cy}`;if(cx>=0&&cy>=0&&cx<this.size&&cy<this.size&&!shots.get(k))this.revealedWater[player-1].add(k);}const won=enemy.every(s=>s.cells.every(([cx,cy])=>shots.get(`${cx},${cy}`)));if(won){this.finished=true;this.winner=player;}else if(!ship)this.player=3-player;return {player,x,y,hit:!!ship,sunk:sunk?ship:null,finished:this.finished,winner:this.winner};}
}
export default class SeaGame {
  constructor(host){this.h=host;this.rules=new SeaRules();this.setupPlayer=1;this.phase='setup';this.selected=0;this.vertical=true;this.hover=null;this.target=null;this.lastShot=null;this.shot=null;this.elapsed=0;this.effects=[new Map(),new Map()];this.clouds=new SeaClouds();this.water=new SeaWaterSurface(host.assets.test_water);this.particles=new SeaParticles();this.setupControls();host.turn(0,'Arrange your ships. Ships cannot touch, even diagonally.');}
  setupControls(){const fleet=this.rules.ships[this.setupPlayer-1];const buttons=this.rules.fleet.map((length,i)=>`<button data-ship="${i}" class="${i===this.selected?'selected':''}">${length} ${fleet[i]?'✓':''}</button>`).join('');this.h.controls(`${this.setupPlayer===1?`<label>Grid <select id="sea-size">${SEA_PRESETS.map(p=>`<option value="${p.size}" ${p.size===this.rules.size?'selected':''}>${p.size} × ${p.size}</option>`).join('')}</select></label>`:''}<div class="ship-picker">${buttons}</div><div class="control-row"><button id="sea-rotate">Rotate ↻</button><button id="sea-random">Arrange for me</button><button id="sea-clear">Clear</button><button id="sea-ready" ${this.rules.arranged(this.setupPlayer)?'':'disabled'}>Fleet ready</button></div>`);this.h.onControl('#sea-size','change',e=>{const preset=SEA_PRESETS.find(p=>p.size===Number(e.currentTarget.value));if(!preset)return;this.rules=new SeaRules(preset.size,preset.fleet);this.effects=[new Map(),new Map()];this.selected=0;this.hover=null;this.setupControls();});this.h.onControl('[data-ship]','click',e=>{this.selected=Number(e.currentTarget.dataset.ship);this.setupControls();});this.h.onControl('#sea-rotate','click',()=>{this.vertical=!this.vertical;this.h.sound('sea_rotate.mp3');});this.h.onControl('#sea-random','click',()=>{this.rules.randomize(this.setupPlayer);this.setupControls();this.h.status('Fleet arranged. You can move any ship before confirming.');});this.h.onControl('#sea-clear','click',()=>{this.rules.clear(this.setupPlayer);this.selected=0;this.setupControls();});this.h.onControl('#sea-ready','click',()=>{if(!this.rules.arranged(this.setupPlayer))return;if(this.setupPlayer===1){this.setupPlayer=2;this.pass('Player 2: arrange your ships',()=>{this.phase='setup';this.selected=0;this.setupControls();this.h.turn(1,'Arrange your ships. Keep them hidden from Player 1.');});}else this.pass('Player 2: begin the battle',()=>this.startAim());});}
  pass(message,next){this.shot=null;this.phase='pass';this.hover=null;this.target=null;this.h.controls(`<button id="sea-pass">${message}</button>`);this.h.status('Pass the device. Tap when the next player is ready.');this.h.onControl('#sea-pass','click',next);}
  startAim(){const continued=this.phase==='result'&&this.lastShot?.hit;this.phase='aim';this.clouds.reset();this.shot=null;this.target=null;if(continued)this.h.status('Hit — choose another target.');else this.h.turn(this.rules.player-1,'Choose your target.');this.h.controls('<p class="instruction">Tap a square, then fire.</p><button id="sea-fire" disabled>Fire!</button>');this.h.onControl('#sea-fire','click',()=>this.fire());}
  get cellSize(){return 340/this.rules.size;}
  coords(p){const cell=this.cellSize,x=Math.floor((p.x-40)/cell),y=Math.floor((p.y-151)/cell);return x>=0&&y>=0&&x<this.rules.size&&y<this.rules.size?{x,y}:null;}
  pointerMove(p){this.hover=this.coords(p);}
  pointerDown(p){const cell=this.coords(p);if(!cell)return;if(this.phase==='setup'){if(this.rules.place(this.setupPlayer,this.selected,cell.x,cell.y,this.vertical)){this.h.sound('sea_editor_put.mp3');const next=this.rules.fleet.findIndex((_,i)=>!this.rules.ships[this.setupPlayer-1][i]);if(next>=0)this.selected=next;this.setupControls();}else this.h.status('Ships must stay on the grid and cannot touch.');}else if(this.phase==='aim'){const key=`${cell.x},${cell.y}`;if(this.rules.shots[this.rules.player-1].has(key)||this.rules.revealedWater[this.rules.player-1].has(key)){this.h.status('This square is already resolved.');return;}this.target=cell;this.h.sound('sea_target.mp3');this.h.controls('<p class="instruction">Target locked. Fire, or choose a different square.</p><button id="sea-fire">Fire!</button>');this.h.onControl('#sea-fire','click',()=>this.fire());}}
  pointerUp(){}
  fire(){if(this.phase!=='aim'||!this.target)return;const {x,y}=this.target,key=`${x},${y}`;if(this.rules.shots[this.rules.player-1].has(key)||this.rules.revealedWater[this.rules.player-1].has(key))return;const cell=this.cellSize;this.shot={...seaFlight(40+(x+.5)*cell,151+(y+.5)*cell,cell),gridX:x,gridY:y,player:this.rules.player};this.lastShot=null;this.phase='flight';this.h.controls('<p class="instruction">Bomb away…</p>');this.h.sound('sea_jet.mp3');}
  update(dt){this.elapsed+=dt;this.clouds.update(dt,!['setup','pass'].includes(this.phase));this.particles.update(dt,this.rules,['setup','pass'].includes(this.phase)?null:(this.shot?.player??this.rules.player));if(!this.shot||this.phase==='result')return;const shot=this.shot;shot.age+=dt;const bombAge=shot.age-shot.releaseAt;if(bombAge>=0&&!shot.released){shot.released=true;this.h.sound('sea_bomb_fall.mp3');}if(bombAge>=SEA_NATIVE.bombDuration&&!shot.impacted){shot.impacted=true;const result=this.rules.fire(shot.gridX,shot.gridY);if(!result){this.shot=null;this.startAim();return;}this.lastShot=result;this.particles.impact(result);this.effects[result.player-1].set(`${result.x},${result.y}`,{hit:result.hit,time:this.elapsed-(bombAge-SEA_NATIVE.bombDuration)});for(const key of this.rules.revealedWater[result.player-1])if(!this.effects[result.player-1].has(key))this.effects[result.player-1].set(key,{hit:false,perimeter:true,time:this.elapsed-(bombAge-SEA_NATIVE.bombDuration)});if(result.hit)shot.shake=makeSeaShake(!!result.sunk);this.phase='impact';this.h.sound(result.sunk?'sea_explosion_big.mp3':result.hit?'sea_explosion.mp3':'sea_hit_water.mp3');this.h.status(result.hit?(result.sunk?'Ship sunk!':'Direct hit!'):'Splash — miss.');}if(shot.impacted&&bombAge>=SEA_NATIVE.bombDuration+SEA_NATIVE.resultDelay){const result=this.lastShot;this.phase='result';if(result.finished){this.h.controls('');this.h.finish(result.winner-1,`Player ${result.winner} sank the enemy fleet!`);}else {this.h.controls(`<button id="sea-next">${result.hit?'Hit — fire again':`Pass to Player ${this.rules.player}`}</button>`);this.h.onControl('#sea-next','click',()=>{if(this.phase!=='result')return;result.hit?this.startAim():this.pass(`Player ${this.rules.player}: ready`,()=>this.startAim());});}}}
  destroy(){this.water.destroy();this.particles.particles=[[],[]];}
  asset(ctx,name,x,y,w,h,alpha=1){const im=this.h.assets[name];if(!im)return false;ctx.save();ctx.globalAlpha*=alpha;ctx.drawImage(im,x,y,w,h);ctx.restore();return true;}
  shotAnimation(ctx){const shot=this.shot;if(!shot)return;const jetX=shot.startX+shot.speed*shot.age,bombAge=shot.age-shot.releaseAt,impactAge=bombAge-SEA_NATIVE.bombDuration;
    if(shot.impacted&&impactAge<.7){if(this.lastShot.hit){const glow=this.h.assets.sea_glow;if(glow){ctx.save();ctx.filter='sepia(1) saturate(6)';const duration=.7,alpha=impactAge<.2?1:1-(impactAge-.2)/.5;ctx.globalAlpha=Math.max(0,alpha);if(this.lastShot.sunk){const ship=this.lastShot.sunk,c=this.cellSize;ctx.translate(40+(ship.x+(ship.vertical?.5:ship.length/2))*c,151+(ship.y+(ship.vertical?ship.length/2:.5))*c);if(!ship.vertical)ctx.rotate(Math.PI/2);ctx.drawImage(glow,-26*2.2*shot.scale/2,-26*ship.length*1.8*shot.scale/2,26*2.2*shot.scale,26*ship.length*1.8*shot.scale);}else {const size=52*shot.scale;ctx.drawImage(glow,shot.x-size/2,shot.y-size/2,size,size);}ctx.restore();}}}
    if(shot.impacted&&!this.lastShot.hit&&impactAge<SEA_NATIVE.rippleDuration){const ripple=seaWaterRipple(impactAge),size=18*ripple.scale*shot.scale;this.asset(ctx,'sea_circ',shot.x-size/2,shot.y-size/2,size,size,ripple.alpha);}
    const bomb=seaBomb(bombAge);if(shot.released&&bomb.visible){ctx.save();ctx.translate(shot.x+bomb.offset*shot.scale,shot.y);ctx.rotate(Math.PI);const w=60*bomb.scale*shot.scale,h=24*bomb.scale*shot.scale;this.asset(ctx,'sea_bomb',-w/2,-h/2,w,h);ctx.restore();}
    if(jetX<520){ctx.save();ctx.translate(jetX,shot.y);ctx.rotate(Math.PI);this.asset(ctx,'sea_jet0',-82.5*shot.scale,-50*shot.scale,165*shot.scale,100*shot.scale);ctx.restore();}
  }
  drawGrid(ctx,x,y,cell,player,showShips,own=false){const size=cell*this.rules.size;if(!this.water.image){ctx.fillStyle='#639ac0';ctx.fillRect(x,y,size,size);}const grid=this.h.assets[SEA_PRESETS.find(p=>p.size===this.rules.size)?.texture||'sea_grid'];if(grid){ctx.globalAlpha=this.phase==='setup'?.35:.6;ctx.drawImage(grid,x,y,size,size);ctx.globalAlpha=1;}ctx.strokeStyle='#3d698c';ctx.lineWidth=1;for(let i=0;i<=this.rules.size;i++){ctx.beginPath();ctx.moveTo(x+i*cell,y);ctx.lineTo(x+i*cell,y+size);ctx.moveTo(x,y+i*cell);ctx.lineTo(x+size,y+i*cell);ctx.stroke();}
    if(showShips)for(const ship of this.rules.ships[player-1])if(ship)this.drawShip(ctx,ship,x,y,cell,1,own&&ship.cells.every(([cx,cy])=>this.rules.shots[2-player].get(`${cx},${cy}`)));
    if(!showShips)for(const ship of this.rules.ships[2-player])if(ship.cells.every(([cx,cy])=>this.rules.shots[player-1].get(`${cx},${cy}`)))this.drawShip(ctx,ship,x,y,cell,1,true);
    if(!own&&!showShips)this.clouds.draw(ctx,this.h.assets.sea_cloud,cell);const shooter=own?2-player:player-1,shots=new Map([...this.rules.revealedWater[shooter]].map(key=>[key,false]));for(const [key,hit] of this.rules.shots[shooter])shots.set(key,hit);for(const [key,hit] of shots){const [cx,cy]=key.split(',').map(Number),px=x+(cx+.5)*cell,py=y+(cy+.5)*cell;const effect=this.effects[shooter].get(key),age=effect?this.elapsed-effect.time:100;if(hit){const targetFleet=this.rules.ships[own?player-1:2-player],destroyed=targetFleet.some(ship=>ship.cells.some(([sx,sy])=>sx===cx&&sy===cy)&&ship.cells.every(([sx,sy])=>this.rules.shots[shooter].get(`${sx},${sy}`)));if(destroyed)continue;const glow=this.h.assets.sea_glow;if(glow){const phase=age%1.02,alpha=phase<.25?phase/.25:phase<.5?2-phase/.25:phase<.51?0:phase<.76?(phase-.51)/.25:phase<1.01?1-(phase-.76)/.25:0;ctx.save();ctx.globalAlpha=alpha;ctx.filter=phase<.51?'sepia(1) saturate(6)':'sepia(1) saturate(8) hue-rotate(320deg)';const size=26*cell/37;ctx.drawImage(glow,px-size/2,py-size/2,size,size);ctx.restore();}else {ctx.fillStyle='#e44832';ctx.beginPath();ctx.arc(px,py,cell*.17,0,Math.PI*2);ctx.fill();}}else {const marker=seaWaterMarker(age,effect?.perimeter),im=this.h.assets.sea_bullet,size=6*cell/37*marker.scale;ctx.save();ctx.globalAlpha=marker.alpha;if(im)ctx.drawImage(im,px-size/2,py-size/2,size,size);else {ctx.fillStyle='#e0f3ff';ctx.beginPath();ctx.arc(px,py,cell*.12,0,Math.PI*2);ctx.fill();}ctx.restore();}}

  }
  drawShip(ctx,ship,x,y,cell,alpha=1,dark=false){ctx.save();ctx.globalAlpha=alpha;if(dark)ctx.filter='brightness(.4)';const w=cell*.82,h=cell*ship.length*.9;const im=this.h.assets[`sea_ship${ship.length}`];if(ship.vertical){ctx.translate(x+(ship.x+.5)*cell,y+(ship.y+ship.length/2)*cell);}else {ctx.translate(x+(ship.x+ship.length/2)*cell,y+(ship.y+.5)*cell);ctx.rotate(Math.PI/2);}if(im)ctx.drawImage(im,-w/2,-h/2,w,h);else {ctx.fillStyle='#4b5c68';ctx.beginPath();ctx.roundRect(-w/2,-h/2,w,h,[cell*.3,cell*.3,cell*.1,cell*.1]);ctx.fill();ctx.fillStyle='#bac9d3';ctx.fillRect(-w*.2,-h*.22,w*.4,h*.35);}ctx.restore();}
  draw(ctx,time){const grad=ctx.createLinearGradient(0,0,0,700);grad.addColorStop(0,'#132d42');grad.addColorStop(1,'#24719c');ctx.fillStyle=grad;ctx.fillRect(0,0,420,700);this.water.draw(ctx,this.elapsed,420,700,this.phase==='setup'?0:2);ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='bold 27px GP, system-ui';ctx.fillText('Sea Battle',210,48);if(this.phase==='pass'){ctx.font='60px GP, system-ui';ctx.fillText('⚓',210,305);ctx.font='22px GP, system-ui';ctx.fillText('Pass the device',210,380);ctx.font='15px GP, system-ui';ctx.fillStyle='#bddcec';ctx.fillText('Keep your fleet hidden.',210,418);return;}
    const cell=this.cellSize,setup=this.phase==='setup',player=setup?this.setupPlayer:(this.shot?.player??(this.phase==='result'?this.lastShot.player:this.rules.player));ctx.font='17px GP, system-ui';ctx.fillStyle='#d1edfc';ctx.fillText(setup?`Player ${player} · Arrange your fleet`:`Player ${player} · Enemy waters`,210,96);ctx.font='12px GP, system-ui';for(let i=0;i<this.rules.size;i++){ctx.fillText(String.fromCharCode(65+i),40+(i+.5)*cell,141);ctx.fillText(String(i+1),27,151+(i+.65)*cell);}ctx.save();const shake=this.shot?.impacted?seaShakeOffset(this.shot.shake,this.shot.age-this.shot.releaseAt-SEA_NATIVE.bombDuration):{x:0,y:0};ctx.translate(shake.x*(this.shot?.scale||1),-shake.y*(this.shot?.scale||1));this.drawGrid(ctx,40,151,cell,player,setup);
    if(setup&&this.hover){const ship={x:this.hover.x,y:this.hover.y,vertical:this.vertical,length:this.rules.fleet[this.selected]};this.drawShip(ctx,ship,40,151,cell,.4);const valid=this.rules.canPlace(player,this.selected,ship.x,ship.y,ship.vertical);ctx.strokeStyle=valid?'#b8f1bc':'#ff655d';ctx.lineWidth=2;ctx.strokeRect(40+ship.x*cell,151+ship.y*cell,cell*(ship.vertical?1:ship.length),cell*(ship.vertical?ship.length:1));}
    if(!setup&&this.target&&!this.shot?.impacted){const im=this.h.assets.sea_target,x=40+this.target.x*cell,y=151+this.target.y*cell;if(im){ctx.save();ctx.translate(x+cell/2,y+cell/2);ctx.rotate(this.elapsed*SEA_NATIVE.targetRadiansPerFrame*60);ctx.drawImage(im,-cell/2-2,-cell/2-2,cell+4,cell+4);ctx.restore();}else {ctx.strokeStyle='#ffed75';ctx.lineWidth=3;ctx.strokeRect(x+2,y+2,cell-4,cell-4);}}
    if(!setup){this.shotAnimation(ctx);this.particles.draw(ctx,this.h.assets.dust_particle,player,cell);}ctx.restore();
    if(setup){ctx.fillStyle='#d4edfb';ctx.font='15px GP, system-ui';ctx.fillText(`Selected: ${this.rules.fleet[this.selected]} squares · ${this.vertical?'vertical':'horizontal'}`,210,537);ctx.font='13px GP, system-ui';ctx.fillText('Select a ship below. Tap its starting square.',210,566);ctx.fillText('Ships cannot touch, even at the corners.',210,588);}else {ctx.fillStyle='#d6ecfc';ctx.font='14px GP, system-ui';ctx.fillText('Your fleet',101,521);this.drawGrid(ctx,40,535,120/this.rules.size,player,true,true);ctx.textAlign='left';const enemy=this.rules.ships[2-player],shots=this.rules.shots[player-1],sunk=enemy.filter(s=>s.cells.every(([x,y])=>shots.get(`${x},${y}`))).length;ctx.fillText(`${sunk} / ${enemy.length} enemy ships sunk`,183,568);ctx.fillText(`${[...shots.values()].filter(Boolean).length} hits · ${shots.size} shots`,183,594);ctx.textAlign='center';}
  }
}
