import './style.css';
import Pool from './games/pool.js';import Sea from './games/sea.js';import Cup from './games/cup.js';import Golf from './games/golf.js';import Connect from './games/connect.js';import Paint from './games/paint.js';import Darts from './games/darts.js';
const catalog=[['pool','8 Ball','pool_preview.jpg',Pool],['sea','Sea Battle','sea_preview.png',Sea],['cup','Cup Pong','beer_preview.png',Cup],['golf','Mini Golf','golf_preview.png',Golf],['connect','Four in a Row','connect_preview.jpeg',Connect],['paint','Paintball','paint_preview.jpg',Paint],['darts','Darts','darts_preview.png',Darts]];
const app=document.querySelector('#app');let game=null, names=JSON.parse(localStorage.getItem('gp-names')||'["Player 1","Player 2"]'),current=null,assets={},paused=false,soundEnabled=localStorage.getItem('gp-sound')!=='off',music=null;
const musicFiles={pool:'music_pool.mp3',sea:'sea_music2.m4a',golf:'golf_music2.m4a',connect:'connect_music.m4a',paint:'paint_music_mixdown7.m4a',darts:'darts_music.mp3'};
function playMusic(id){music?.pause();music=null;if(musicFiles[id]){music=new Audio('./assets/'+musicFiles[id]);music.loop=true;music.volume=.12;if(soundEnabled)music.play().catch(()=>{});}}
async function loadAssets(){const files=await fetch('./assets/manifest.json').then(r=>r.json());await Promise.all(files.filter(f=>/\.(png|jpg|jpeg|gif)$/.test(typeof f==='string'?f:f.path)).map(f=>new Promise(resolve=>{const path=typeof f==='string'?f:f.path;const im=new Image();im.onload=()=>{assets[path.split('/').pop().replace(/\.[^.]+$/,'')]=im;resolve()};im.onerror=resolve;im.src='./assets/'+path})));}
function header(title='GamePigeon'){return `<header>${game?'<button id="back">‹ Games</button>':'<h1>GamePigeon</h1>'}${game?`<h1>${title}</h1>`:''}<button id="sound" aria-label="Toggle sound">${soundEnabled?'♫':'♪'}</button></header>`;}
function wireHeader(){document.querySelector('#sound').onclick=()=>{soundEnabled=!soundEnabled;localStorage.setItem('gp-sound',soundEnabled?'on':'off');if(music){if(soundEnabled)music.play().catch(()=>{});else music.pause();}document.querySelector('#sound').textContent=soundEnabled?'♫':'♪'};const b=document.querySelector('#back');if(b)b.onclick=()=>{game?.destroy?.();game=null;paused=false;document.querySelector('.overlay')?.remove();home()};}
function home(){layoutObserver.disconnect();music?.pause();music=null;app.className='home-page';app.innerHTML=header()+`<div class="names">${names.map((n,i)=>`<label>Player ${i+1}<input maxlength="20" id="name${i}" value="${escape(n)}"></label>`).join('')}</div><div class="grid">${catalog.map(([id,title,img])=>`<button class="game-card" data-game="${id}"><img src="./assets/${img}" alt=""><span>${title}</span></button>`).join('')}</div>`;wireHeader();document.querySelectorAll('.game-card').forEach(b=>b.onclick=()=>{names=names.map((n,i)=>document.querySelector('#name'+i).value.trim()||`Player ${i+1}`);localStorage.setItem('gp-names',JSON.stringify(names));start(b.dataset.game)});}
function escape(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function modal(title,message,buttons){paused=true;document.querySelector('.overlay')?.remove();const el=document.createElement('div');el.className='overlay';el.innerHTML=`<div class="modal"><h2>${escape(title)}</h2><p>${escape(message)}</p>${buttons.map((b,i)=>`<button class="${i===0?'primary':''}" data-i="${i}">${escape(b[0])}</button>`).join('')}</div>`;document.body.append(el);el.querySelectorAll('button').forEach(b=>b.onclick=()=>{el.remove();paused=false;buttons[+b.dataset.i][1]()});}
function start(id){layoutObserver.disconnect();playMusic(id);current=catalog.find(g=>g[0]===id);game?.destroy?.();game={};app.className='game-page';app.innerHTML=header(current[1])+`<main class="stage"><div class="scorebar">${names.map((n,i)=>`<span class="player ${i===0?'active':''}" data-player="${i}">${escape(n)}</span>`).join('')}</div><p class="status"></p><div class="game-layout"><div class="board-space"><canvas width="420" height="700" aria-label="${current[1]} game board"></canvas></div><aside class="control-space" aria-label="Game controls"><div class="controls"></div></aside></div></main>`;wireHeader();const canvas=document.querySelector('canvas');const host={canvas,ctx:canvas.getContext('2d'),assets,names,status(s){document.querySelector('.status').textContent=s},turn(p,message){if(message)document.querySelector('.status').textContent=message;document.querySelectorAll('.player').forEach((el,i)=>el.classList.toggle('active',i===p));if(id!=='sea'&&id!=='connect')modal(`Pass to ${names[p]}`,message||'Ready for your turn?',[['Ready',()=>{}]])},finish(winner,message){modal(winner===null?'Draw!':`${names[winner]} won!`,message||'Play again?',[['Play again',()=>start(id)],['Games',()=>{game?.destroy?.();game=null;home()}]])},sound(file,volume=.45){if(soundEnabled){const a=new Audio('./assets/'+file);a.volume=Math.max(0,Math.min(1,volume));a.play().catch(()=>{})}},controls(html){document.querySelector('.controls').innerHTML=html;requestAnimationFrame(fitStage)},onControl(sel,event,fn){document.querySelector('.controls').querySelectorAll(sel).forEach(el=>el.addEventListener(event,fn))}};game=new current[3](host);requestAnimationFrame(fitStage);document.querySelectorAll(".board-space,.control-space").forEach(el=>layoutObserver.observe(el));function point(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*420/r.width,y:(e.clientY-r.top)*700/r.height}}canvas.onpointerdown=e=>{if(!paused){canvas.setPointerCapture(e.pointerId);game.pointerDown?.(point(e))}};canvas.onpointermove=e=>{if(!paused)game.pointerMove?.(point(e))};canvas.onpointerup=e=>{if(!paused)game.pointerUp?.(point(e))};canvas.onpointercancel=()=>game.pointerCancel?.();}
function fitStage(){const box=document.querySelector('.board-space'),canvas=box?.querySelector('canvas'),controls=document.querySelector('.controls'),side=document.querySelector('.control-space');if(!canvas)return;const width=Math.max(1,Math.min(box.clientWidth,box.clientHeight*420/700));canvas.style.width=`${width}px`;canvas.style.height=`${width*700/420}px`;if(controls&&side){controls.style.zoom=1;controls.style.zoom=Math.min(1,Math.max(.1,(side.clientHeight-8)/Math.max(1,controls.scrollHeight)));}}
const layoutObserver=new ResizeObserver(()=>requestAnimationFrame(fitStage));
window.addEventListener('resize',()=>requestAnimationFrame(fitStage));document.addEventListener('toggle',()=>requestAnimationFrame(fitStage),true);
let prev=0;function tick(ms){const dt=Math.min((ms-prev)/1000,.03);prev=ms;if(game?.draw){if(!paused)game.update?.(dt,ms/1000);game.draw(document.querySelector('canvas').getContext('2d'),ms/1000)}requestAnimationFrame(tick)}
app.innerHTML='<div class="intro"><h2>Loading games…</h2></div>';await Promise.all([loadAssets(),document.fonts.load('16px GP'),document.fonts.load('bold 16px GP')]);home();requestAnimationFrame(tick);
